sudo: required
dist: trusty
os: linux
language: generic

before_install:
  - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
install:
  - sudo apt-get update
script:
  - make all
after_script:
  - echo $TRAVIS_COMMIT_RANGE
