sudo: required

dist: trusty

os: linux

language: generic

before_install:
- echo 'before_install'

install:
- echo 'install'

before_script:
- echo 'before_script'

script:
- echo 'script'

after_script:
- echo 'after_script'
