sudo: false

language: generic

osx_image: xcode8

dist: trusty

env:
  global:
  - A=one
  matrix:
  - B=two

os:
- linux
- osx

before_install:
- echo 'before_install'

install:
- echo 'install'

before_script:
- echo 'before_script'

script:
- echo 'script'

after_script:
- echo 'after_script'
