sudo: required
dist: trusty
os: linux
language: generic

before_install:
  - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
install:
  - sudo curl https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update
  - sudo apt-get install yarn
  - nvm install
before_script:
  - nvm use
  - yarn install
script:
  - make all
after_script:
  - echo $TRAVIS_COMMIT_RANGE
