sudo: required
dist: trusty
os: linux
language: generic

before_install:
  - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
install:
  - if [ -n "$PPA" ]; then travis_retry sudo add-apt-repository "$PPA" -y; fi
  - if [ -n "$DPKG_ADD_ARCH" ]; then sudo dpkg --add-architecture "$DPKG_ADD_ARCH" ; fi
  - if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get update; fi
  - if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends --no-upgrade -qq $PACKAGES; fi
  - nvm install
before_script:
  - nvm use
script:
  - make all
after_script:
  - echo $TRAVIS_COMMIT_RANGE
