sudo: required
dist: trusty
language: generic
os: linux

matrix:
  - PACKAGES="yarn"

before_install:
  - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")

install:
  - nvm install && nvm use && npm i -g yarn && yarn install

before_script:
  - clang --version

script:
  - make all

after_script:
  - echo $TRAVIS_COMMIT_RANGE
