RUN "apt-get update"
#RUN "apt-get -y upgrade 2> /dev/null"
RUN "apt-get -y install build-essential 2> /dev/null"
#RUN "apt-get -y install llvm 2> /dev/null"
#RUN "apt-get -y install clang 2> /dev/null"
RUN "apt-get -y install libssl-dev libffi-dev 2> /dev/null"
RUN "apt-get -y install git 2> /dev/null"
RUN "apt-get -y install curl 2> /dev/null"
RUN "apt-get -y install apt-transport-https 2> /dev/null"
RUN "apt-get -y install ca-certificates"
EXIT_SUCCESS
