RUN "apt-get update"
RUN "apt-get -y upgrade $BOOT_DEBUG"
RUN "apt-get -y install build-essential $BOOT_DEBUG"
RUN "apt-get -y install llvm $BOOT_DEBUG"
RUN "apt-get -y install clang $BOOT_DEBUG"
RUN "apt-get -y install libffi-dev $BOOT_DEBUG"
RUN "apt-get -y install libssl-dev $BOOT_DEBUG"
RUN "apt-get -y install git $BOOT_DEBUG"
RUN "apt-get -y install curl $BOOT_DEBUG"
RUN "apt-get -y install apt-transport-https $BOOT_DEBUG"
RUN "apt-get -y install ca-certificates $BOOT_DEBUG"
EXIT_SUCCESS
