name: news.code

meta:
- type: namespace
- kind: domain
- identity: false

control:
- blockstack: false
- centralized: true
- dns: true
- icann: true

registrant:
  name: DeSantis Inc.
  meta:
  - type: company
  - kind: tech

uris:
  handlers:
  - deos://news.code/index.html
  - Δ://news/code/index.html
  hyperlinks:
  - https://code.news
  - https://Δ.ws/news/code
  keys:
  - deos:news:code:index
  - Δ:news:code:index
  paths:
  - /var/root/news/code/
