name: id.desantis

meta:
- type: namespace
- kind: domain
- identity: true

control:
- blockstack: true
- centralized: false
- dns: true
- icann: false

uris:
  handlers:
  - deos://id.desantis/index.html
  - Δ://id/desantis/index.html
  hyperlinks:
  - https://desantis.id
  - https://Δ.ws/id/desantis
  keys:
  - deos:id:desantis:index
  - Δ:id:desantis:index
  paths:
  - /var/root/id/desantis/
