name: com.twitter

meta:
- type: namespace
- kind: domain
- identity: false

dates:
- created: 2000-01-21T16:28:17Z
- expires: 2020-01-21T16:28:17Z
- updated: 2016-11-08T05:07:31Z

control:
- blockstack: false
- centralized: true
- dns: true
- icann: true

registrant:
  name: Twitter, Inc.
  meta:
  - type: company
  - kind: media
  address:
  - street: 1355 Market St
  - city: San Francisco
  - state: CA
  - postal: 94103
  - country: US
  contact:
  - email: domains@twitter.com
  - fax: +1(415)222-0922
  - phone: +1(415)222-9670

uris:
  handlers:
  - deos://com.twitter/index.html
  - Δ://com/twitter/index.html
  hyperlinks:
  - https://twitter.com
  - https://Δ.ws/com/twitter/index.html
  keys:
  - deos:com:twitter:index
  - Δ:com:twitter:index
  paths:
  - /var/root/com/twitter/
