type: xml
version: 1.0
encoding: UTF-8
body:
  type: ui
  version: 4.0
  list:
  - type: class
    value: AddPasswordDialog
  - type: widget
    class: QDialog
    name: AddPasswordDialog
    list:
    - type: property
      name: geometry
      list:
      - type: rect
        x: 0
        y: 0
        width: 400
        height: 266
    - type: property
      name: windowTitle
      list:
        - type: string
          value: Add/edit password
    - type: layout
      name: verticalLayout
      class: QVBoxLayout
      list:
      - type: item
        list:
        - type: widget
          name: label
          class: QLabel
          list:
          - type: property
            name: text
            list:
            - type: string
              value: Key
        - type: widget
          name: keyEdit
          class: QLineEdit
          list:
          - type: property
            name: maxLength
            list:
            - type: number
              value: 64
        - type: widget
          name: label_2
          class: QLabel
          list:
          - type: property
            name: text
            list:
            - type: string
              value: Password/value
            - type: property
              name: echoMode
              list:
                type: enum
                value: QLineEdit::Password
        - type: widget
          name: pwEdit1
          class: QLineEdit
          list:
          - type: property
            name: maxLength
            list:
            - type: number
              value: 64
          - type: property
            name: echoMode
            list:
            - type: enum
              value: QLineEdit::Password
        - type: widget
          name: label_3
          class: QLabel
          list:
          - type: property
            name: text
            list:
            - type: string
              value: Repeat password/value
            - type: property
              name: echoMode
              list:
                type: enum
                value: QLineEdit::Password
        - type: widget
          name: pwEdit2
          class: QLineEdit
          list:
          - type: property
            name: text
            list:
            - type: string
          - type: property
            name: maxLength
            list:
            - type: number
              value: 64
          - type: property
            name: echoMode
            list:
            - type: enum
              value: QLineEdit::Password
        - type: layout
          class: QHBoxLayout
          name: horizontalLayout
          list:
          - type: item
            list:
            - type: spacer
              name: horizontalSpacer
              list:
              - type: property
                name: orientation
                list:
                - type: enum
                  value: Qt::Horizontal
              - type: property
                name: sizeHint
                stdset: 0
                list:
                - type: size
                  width: 40
                  height: 20
            - type: widget
              class: QPushButton
              name: showHideButton
              list:
              - type: property
                name: text
                list:
                - type: string
                  value: Show/hide
        - type: spacer
          name: verticalSpacer
          list:
          - type: property
            name: orientation
            list:
            - type: enum
              value: Qt::Vertical
          - type: property
            name: sizeHint
            stdset: 0
            list:
            - type: size
              width: 20
              height: 40
        - type: widget
          name: buttonBox
          class: QDialogButtonBox
          list:
          - type: property
            name: orientation
            list:
            - type: enum
              value: Qt::Horizontal
          - type: property
            name: standardButtons
            list:
            - type: set
              value: QDialogButtonBox::Cancel|QDialogButtonBox::Ok
  - type: resources
  - type: connections
    list:
    - sender: buttonBox
      signal: accepted()
      receiver: AddPasswordDialog
      slot: accept()
      hints:
      - type: sourcelabel
        x: 257
        y: 239
      - type: destinationlabel
        x: 157
        y: 274
    - sender: buttonBox
      signal: rejected()
      receiver: AddPasswordDialog
      slot: reject()
      hints:
      - type: sourcelabel
        x: 325
        y: 239
      - type: destinationlabel
        x: 286
        y: 274
