xml:
  version: 1.0
  encoding: UTF-8

ui:
  version: 4.0
  class: AddPasswordDialog
  type: widget
  AddPasswordDialog:
    class: QDialog
    property:
      geometry:
        rect:
          x: 0
          y: 0
          width: 400
          height: 226
      windowTitle: Add/edit password
    layout:
      verticalLayout:
        class: QVBoxLayout
