type: object
required: [makeflags, default_goal, phony, sublime_targets, config_file, all]
properties:
  makeflags: {type: string}
  default_goal: {type: string}
  phony: {type: string}
  sublime_targets: {type: string}
  config_file: {type: string}
  all:
    type: object
    required: [hook, 'if:host;is:mac', else]
    hook:
      type: object
      required: [pre, post]
